language: java

jobs:
  include:
    - stage: CodeQuality
      script: ./gradlew sonarqube
addons:
  sonarcloud:
    organization: $SONAR_USER
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

jdk:
  - openjdk11